### ISSUE TITLE
Can't load WebRTC native plugin on the Mac

### ISSUE THREAD

**Issue by poke646** [godotengine/webrtc-native#117]
### Godot version

4.1.1

### Plugin version

Latest Official Build

### System information

Mac OS 13.3.1 (Ventura) M1 PRO

### Issue description

I tried the official webrtc demo project. 

Downloaded the native webrtc plugin and copied to root folder of the project.

On Debug start there is an error: Error loading extension: res://webrtc.gdextension

### Steps to reproduce

Unpack the sample and put official libs to lib folder in the project.
Run the project on Mac M1.

### Minimal reproduction project

[sample-rtc-project.zip](https://github.com/godotengine/webrtc-native/files/12642632/sample-rtc-project.zip)

**Comment by poke646** [comment]
Oh I see the folder structure seems wrong it should be in "webrtc" folder but I can't run demo because of 
WebSocketClient not declared in the current scope. on multiplayer_client.gd

**Comment by Faless** [comment]
> Oh I see the folder structure seems wrong it should be in "webrtc" folder

This issue is also being tracked in #118 and there is a bit more information there.

> WebSocketClient not declared in the current scope

WebSocket classes have changed in Godot 4.0, check the updated demo [here](https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_signaling)
