### ISSUE TITLE
Support for unit tests?

### ISSUE THREAD

**Issue by CatsNipYummy** [godotengine/webrtc-native#15]
Is it possible to add unit tests to this repo to quickly test out some functionality?

**Comment by Faless** [comment]
I don't think there's much to be unit tested in this repository, which function do you have in mind that needs unit testing?

**Comment by CatsNipYummy** [comment]
Something similar to what the webrtc repository does? Perhaps have a server and 2 client scripts (in C++) to check if the channels have been established and the data is transferred between the two?

**Comment by Faless** [comment]
Well, that's not really unit testing, it's more integration testing, and
should be done while testing the engine as the plugin can't work without
the engine.
The simple webrtc demo in the official Godot demo repository could be used
for that, but first, a standardized way of testing the engine itself should
be decided on. There is ongoing discussion about it in the godot repository
IIRC.

**Comment by Faless** [comment]
Closing as this is outside of the scope of this repository.
