### ISSUE TITLE
deriving from WebRTCPeerConnection (in c#) results in runtime error during construction.

### ISSUE THREAD

**Issue by ASavchenkov** [godotengine/webrtc-native#19]
Godot version 3.2.2
Error as follows:

> E 0:00:00.625   set_script_and_instance: Condition "script_instance != __null || !script.is_null()" is true.
>  <C++ Source>  core/object.cpp:1008 @ set_script_and_instance()
>  <Stack Trace> :0 @ IntPtr Godot.NativeCalls.godot_icall_WebRTCPeerConnection_Ctor(Godot.WebRTCPeerConnection )()
>                WebRTCPeerConnection.cs:52 @ Godot.WebRTCPeerConnection..ctor()()
>               Spatial.cs:9 @ Spatial+WebRTCBar..ctor()()
>               Spatial.cs:17 @ void Spatial._Ready()()

Minimal reproduction project below:
[WebRTCPeerConnectionIssue.zip](https://github.com/godotengine/webrtc-native/files/4996947/WebRTCPeerConnectionIssue.zip)

**Comment by Faless** [comment]
I think this is simply not possible (even with GDScript) since the native plugin is implemented as a c++ script attached to a `WebRTCPeerConnectionGDNative` object. And in Godot you can only have one script attached to each object.

**Comment by Faless** [comment]
> I think this is simply not possible (even with GDScript)

Now possible with the GDExtension version (Godot 4), since GDExtension does not require the C++ code to act as a script.
