### ISSUE TITLE
Difficulty compiling on Windows - /MD vs /MT

### ISSUE THREAD

**Issue by lewiji** [godotengine/webrtc-native#25]
Firstly, my C++ skills are very rusty (last used it about 10 years ago for any actual development work) and I'm not experienced at all in these builds systems, so if I missed something obvious please say so.

Building Linux and Android binaries on a 64 bit Linux host went relatively smoothly, though I did have to dig around in the godot-cpp pull requests, issues and commit history in order to find a build config that worked. 

On a Windows host, building Windows binaries, I struggled a lot and eventually succeeded.

The precompiled `libwebrtc-full` binaries don't seem to work when compiling webrtc-native for and on Windows, with the complaint that a static release library doesn't match to the dynamic release target. So, I though I'd compile libwebrtc myself.

Since the [linked script from the readme](https://github.com/Faless/webrtc-builds) doesn't seem to work any more (fails to sync from google), I ended up following the [instructions from Microsoft](https://docs.microsoft.com/en-us/winrtc/getting-started) up to "Downloading the bits" (ie syncing the branch with gclient), then copying in the build/util scripts and tools from the `webrtc-builds` repo, modifying them to properly work with VS2017, and eventually getting a working build - only to find that they, too, were statically linked and didn't work on a dynamic target. The specific error was:

`error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease'`

`warning LNK4098: defaultlib ‘LIBCMT’ conflicts with use of other libs; use /NODEFAULTLIB:library`

Given that the build targets for the godot-cpp and webrtc-native projects seemed to be explicitly using the /MD and /MDd linker options, I tried to see if I could build webrtc using the /MD flag - it seems this isn't possible as the project explicitly ignores the `is_component_build`, with a Google engineer basically saying "well whatever project you're building with should support a /MT binary", which wasn't too helpful.

Finally I did the obvious thing and changed the `godot-cpp` and `webrtc-native` scripts for Windows linkage to use /MT and /MTd instead, whereupon the build worked and I got a binary out of the thing. I'm just wondering if I've set myself up for some unexpected behaviour by doing so, though the gdnative dll seems to work.

All in all - wondering if there are any changes here worth making a pull request for, or investigating further.

**Comment by Faless** [comment]
>  I'm just wondering if I've set myself up for some unexpected behaviour by doing so, though the gdnative dll seems to work.

Yeah, the official webrtc-native plugin distribution is also using `/MT` and `/MTd` for the `godot-cpp`, so you'll be fine.
I know this is an issue, so I'll leave this open.
I haven't found much time work on the plugin recently, I hope to improve it in the coming months, I've been considering using another library that's much easier to maintain but had no luck with it yet.

**Comment by Faless** [comment]
This is fixed in the last [release](https://github.com/godotengine/webrtc-native/releases/tag/0.5) and [webrtc library](https://github.com/Faless/webrtc-builds/releases/tag/4472-33644-92ba70c) which builds WebRTC with dynamic runtime.
