### ISSUE TITLE
WebRTC library stuck on running hooks.

### ISSUE THREAD

**Issue by drwhut** [godotengine/webrtc-native#29]
I'm trying to compile the WebRTC library with the script mentioned in the README on Linux (x64) with the command `./build.sh -b branch-heads/68`, and part-way through the script it gets stuck at this line (for at least an hour):

```
Running hooks:  90% (27/30) msan_chained_origins
```

And after using Ctrl+C:
```
Failed while running "vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1"
Interrupted
Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' took 949.56 secs
```

I've also tried compiling the latest version of the library (which works), but the GDNative library doesn't work with it.

Is there a workaround for this? Should I build a different version of WebRTC?

**Comment by Faless** [comment]
It's not stuck. It just takes ages.

Anyway, the new [`0.5 release`](https://github.com/godotengine/webrtc-native/releases/tag/0.5) has been updated to use WebRTC `branch-heads/4472`. Not that it's any faster,...
