### ISSUE TITLE
0.3 Plugin error: 'WebRTCDataChannel' is not a valid type in Win 10 Godot Engine v3.1.1.stable

### ISSUE THREAD

**Issue by tomoprime** [godotengine/webrtc-native#5]
After importing plugin zip into an empty project folder WebRTCNativeDemo I get error:
> Godot Engine v3.1.1.stable.official (c) 2007-2019 Juan Linietsky, Ariel Manzur & Godot Contributors.
 res://scripts/SimplePeer.gd:42 - Parse Error: Identifier 'WebRTCDataChannel' is not a valid type (not a script or class), or could not be found on base 'self'.
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
Switch Scene Tab

Am I missing something? Sorry I'm new to using Godot 3.1.1 let alone to using GDNative.
Will I even need the WebRTC plugin if switching to Godot 3.2 Alpha 2 then?

**Comment by tomoprime** [comment]
Update: running the above project in Godot 3.2 Alpha 2 has no issues as expected.

**Comment by Faless** [comment]
Webrtc is simply not supported in 3.1 .
It's a new feature in 3.2.

**Comment by tomoprime** [comment]
it is strange. I started up a nodejs instance on a mac. 
https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_signaling/server_node

Then on Windows I connected to it with Godot 3.2 for the webrtc_signaling demo using the address of the mac. But I was only able to see each peer listed separately. Without the adding this GDNative plugin to the webrtc_signaling demo project folder.

After adding this plug as required. The webrtc_signaling demo cannot make a connection to the Mac that is running the nodejs server code.

ERROR: _get_socket_error: Socket error: 10022
   At: drivers/unix/net_socket_posix.cpp:198
ERROR: connect_to_host: Connection to remote host failed!
   At: drivers/unix/net_socket_posix.cpp:425
Signaling server disconnected: 1000 - Unknown
Disconnected: 1000: Unknown

**Comment by Faless** [comment]
That error does not seem related to this plugin. It happens during the
connection to the signaling server (websocket) and the error (10022) is
usually a windows or network problem.
Double check your connection to the Mac, the IP/port, try disabling
firewall, antivirus, etc.

**Comment by tomoprime** [comment]
All I know is that the remote WebRTC signaling demo works once I disable the plugin. It even worked before installing plugin. No changes were made to my network. I can replicate it on demand by toggling on/off webrtc.tres inside of a Project Settings->GDNative. 


On Oct 18, 2019, at 5:18 AM, Fabio Alessandrelli <notifications@github.com> wrote:

That error does not seem related to this plugin. It happens during the
connection to the signaling server (websocket) and the error (10022) is
usually a windows or network problem.
Double check your connection to the Mac, the IP/port, try disabling
firewall, antivirus, etc.

**Comment by Faless** [comment]
I see... you are using 3.2 alpha 2 right?
I'll make a build for that alpha specifically and post the link to test
potentially binary compatibility issues.
Still, there should be no issue, so it's really weird.
You are using the latest release of the plugin right? 0.3

**Comment by tomoprime** [comment]
Yes to both using latest binaries for Windows 10. I did not compile from source. 

I played the demo in Godot in Windows 10 after running a:
npm install
node server.js 

On another machine (macOS)

Signaling Demo:
https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_signaling


On Oct 18, 2019, at 4:34 PM, Fabio Alessandrelli <notifications@github.com> wrote:

I see... you are using 3.2 alpha 2 right?
I'll make a build for that alpha specifically and post the link to test
potentially binary compatibility issues.
Still, there should be no issue, so it's really weird.
You are using the latest release of the plugin right? 0.3

**Comment by tomoprime** [comment]
Sorry just wanted to note I had used the 64bit build of Windows with the 0.3 Plugin release.
https://downloads.tuxfamily.org/godotengine/3.2/alpha2/Godot_v3.2-alpha2_win64.exe.zip

**Comment by tomoprime** [comment]
Sorry if this appears as a duplicate msg as my last post was lost somehow. Just wanted to point out I had used the [Win64](https://downloads.tuxfamily.org/godotengine/3.2/alpha2/Godot_v3.2-alpha2_win64.exe.zip) binary of Godot 3.2 Alpha 2 with the prebuilt v0.3 WebRTC plugin.

**Comment by tomoprime** [comment]
Note I had only tested Signaling in that example. I just checked out your **bomber-rtc** demo to gain some more clarity on what works...

When I:
Enable the webrtc-native plugin:
- Local Signaling and WebRTC works
- Remote Signaling fails 

Disable the webrtc-native plugin:
- Remote Signaling works but WebRTC fails

**Comment by dryw** [comment]
I can confirm the above behaviour both in 3.2 Alpha 1 and Alpha 2. **bomber-rtc** works as expected in linux but on windows I get the following errors:

webrtc-native plugin disabled:
- Windows client connects to signalling server and receives a lobby ID.
- Throws an ERR_UNCONFIGURED error when an RPC is made (to be expected)

webrtc-native plugn enabled:
- Socket error 10022 (drivers/unix/net_socket_posix.cpp:197 @ _get_socket_error())
- Signalling server does not even see the request

This seems to be the case for both 32/64 bit windows. 

Will look into rebuilding the plugin against the latest headers. Let me know if there's any specific debugging information that would be helpful!

**Comment by tomoprime** [comment]
@dryw Thank you for testing my Windows case as well. It's good to know Linux is ok. I was trying to build the plugin for MacOS but the native code reference for the [webrtc_ios](https://webrtc.org/native-code/ios/) target was pushing over 10GB to download on my machine and I ran out of disk space. They say you need under 6GB but my sync grew much larger. 

Btw I tested a different port when trying the bomber example on Heroku which might work on linux, 
e.g.: `ws://bomber-rtc.herokuapp.com`

Heroku sets it's own ports so you must update line 6 in **server.js** to load by ENV:
 `const PORT = process.env.PORT || 9080;`

Note: @Faless it may be ideal to create an external _bomber-rtc_ app on free [Heroku](https://www.heroku.com) to test remote Signaling code changes for godot. The URL given above isn't set up as I reserved a different name to test so not to take over ownership.

**Comment by Faless** [comment]
Discussion moved to a separate issue (#6).
Clsoing.
