### ISSUE TITLE
v1.0.0-alpha1 for godot3 for windows instead of dll files are so files at lib folder, and not working at godot 3.4.4 after renaming to dll

### ISSUE THREAD

**Issue by XDRiVE888** [godotengine/webrtc-native#52]
### Godot version

v3.4.4.stable.official [419e713a2]

### Plugin version

1.0.0-alpha1

### System information

Windows 10

### Issue description

webrtc plugin v1.0.0-alpha1 for godot3 for windows instead of dll files are so files at lib folder, and not working at godot 3.4.4 after renaming .so to .dll

### Steps to reproduce

Try to starts any godot3 windows progect with webrtc plugin 1.0.0-alpha1 e.g. at godot editor.

**Comment by Faless** [comment]
Please note that as per release notes the current release (`
v1.0.0-alpha1`) might not work with Godot 3.4, can you try with the latest 3.5 release candidate?
I'll fix the naming, but the binary should actually be correct.

**Comment by Faless** [comment]
I can confirm it does not work with 3.5 either. Will investigate

**Comment by Faless** [comment]
Should be fixed in version [`1.0.0=alpha2`](https://github.com/godotengine/webrtc-native/releases/tag/1.0.0-alpha2)
