### ISSUE TITLE
The SConstruct does not work for osx platform

### ISSUE THREAD

**Issue by BimDav** [godotengine/webrtc-native#59]
### Godot version

3.4.4-stable

### Plugin version

master

### System information

MacOS, M2

### Issue description

scons platform=osx target=release -j6 arch=arm64

errors with

clang: error: no such file or directory: 'deps/build/osx.release.arm64.dir/libdatachannel/libdatachannel-static.a'
clang: error: no such file or directory: 'deps/build/osx.release.arm64.dir/libdatachannel/deps/libjuice/libjuice-static.a'
clang: error: no such file or directory: 'deps/build/osx.release.arm64.dir/libdatachannel/deps/libsrtp/libsrtp2.a'
clang: error: no such file or directory: 'deps/build/osx.release.arm64.dir/libdatachannel/deps/usrsctp/usrsctplib/libusrsctp.a'

scons platform=osx target=release -j6  

errors with 

scons: *** [deps/build/osx.release.universal.dir/openssl/libssl.a] ValueError : macOS architecture not supported: universal

scons platform=osx target=release -j6 arch=x86_64

errors with 

clang: error: no such file or directory: 'deps/build/osx.release.x86_64.dir/libdatachannel/libdatachannel-static.a'
clang: error: no such file or directory: 'deps/build/osx.release.x86_64.dir/libdatachannel/deps/libjuice/libjuice-static.a'
clang: error: no such file or directory: 'deps/build/osx.release.x86_64.dir/libdatachannel/deps/libsrtp/libsrtp2.a'
clang: error: no such file or directory: 'deps/build/osx.release.x86_64.dir/libdatachannel/deps/usrsctp/usrsctplib/libusrsctp.a'
clang: error: no such file or directory: 'deps/build/osx.release.x86_64.dir/openssl/libssl.a'
clang: error: no such file or directory: 'deps/build/osx.release.x86_64.dir/openssl/libcrypto.a'

### Steps to reproduce

run the above commands

**Comment by Anutrix** [comment]
Same issue on Windows

**Comment by BimDav** [comment]
> Same issue on Windows

with arch=x86_64, it works now for me. I think there was an error message lost somewhere in the logs that I did not have `make` installed, maybe try that?

for the default arch, which is universal for the macos target, the sconstruct still does not work so I leave the issue open

**Comment by mattkanwisher** [comment]
Ok for me it was having trouble finding the Cmake binary from homebrew. I have a hack below, i'm sure a smarter person will find a cleaner way to get the pathing to work

```bash 
which cmake
sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake
```
