### ISSUE TITLE
NetSocket connect_to_host fails on windows when plugin is enabled

### ISSUE THREAD

**Issue by Faless** [godotengine/webrtc-native#6]
From @dryw cfr: https://github.com/godotengine/webrtc-native/issues/5#issuecomment-545492921
> webrtc-native plugin disabled:
> 
>     Windows client connects to signalling server and receives a lobby ID.
>     Throws an ERR_UNCONFIGURED error when an RPC is made (to be expected)
>     Even just building and then deleting the copied-over webRTC dll will get you to this state.
> 
> webrtc-native plugin enabled:
> 
>     Socket error 10022 (drivers/unix/net_socket_posix.cpp:197 @ _get_socket_error())
>     Signalling server does not even see the request
> 

And @tomoprime https://github.com/godotengine/webrtc-native/issues/5#issuecomment-545704910

I (@Faless) can too confirm this issue.

I suspect the "beautiful" windows socket subsytem to be the cause. I'm investigating...

**Comment by dryw** [comment]
I cherry picked faless/godot@abcb0798d6ef5005ec6308db0dd6032220a1f873 into the latest godot master https://github.com/godotengine/godot/commit/930d6d8ca4c34b0383d232335902f7f808806a66 and recompiled. I can confirm that WebRTC now appears to function normally on windows.

Tested both the regular multiplayer bomber demo and the RTC version.

@Faless: Thanks you very much! I'd be happy to do more testing, if required.

**Comment by dryw** [comment]
@Faless: After doing some additional testing, it looks like the `connection_error()` signal is no longer emitted if the connection fails during the initial connection. If the server disconnects after a connection is successful, `connection_closed()` seems to fire just fine.

Reproduced with **bomber_rtc** example.

**Comment by Faless** [comment]
> After doing some additional testing, it looks like the `connection_error()` signal is no longer emitted if the connection fails during the initial connection.

That seems to be a different issue (it happens on alpha2 without the fix, and with the plugin disabled), please open a new issue in the appropriate repository (either demo projects as a start, or godot repo directly if you can confirm it's a bug in `WebSocketClient.connect_to_url`).

**Comment by dryw** [comment]
@Faless: I agree that this is a different issue having to do with `WebSocketClient` rather than WebRTC. I will try to reproduce and open an issue on the appropriate repo. Thanks!

**Comment by Faless** [comment]
Closed via https://github.com/godotengine/godot/pull/33070

**Comment by tomoprime** [comment]
Thanks all. Did the fix make into yesterdays Alpha 3 release? Or direct to where / how I should test on my end.
