### ISSUE TITLE
Is is possible to make a build for every Godot 4.0 beta?

### ISSUE THREAD

**Issue by maxim-sheronov** [godotengine/webrtc-native#62]
### Godot version

4.0 beta2

### Plugin version

latest

### System information

windows 10

### Issue description

Hi there.

I cannot build it for beta2 on my own. Maybe it's possible to make a build for every beta?
Or maybe make a better explanation on build process.

If you are interested, I got this errors:
x86_64-w64-mingw32-g++: error: deps/build/windows.debug.x86_64.dir/libdatachannel/libdatachannel-static.a: No such file or directory
x86_64-w64-mingw32-g++: error: deps/build/windows.debug.x86_64.dir/libdatachannel/deps/libjuice/libjuice-static.a: No such file or directory
x86_64-w64-mingw32-g++: error: deps/build/windows.debug.x86_64.dir/libdatachannel/deps/libsrtp/libsrtp2.a: No such file or directory
x86_64-w64-mingw32-g++: error: deps/build/windows.debug.x86_64.dir/libdatachannel/deps/usrsctp/usrsctplib/libusrsctp.a: No such file or directory
x86_64-w64-mingw32-g++: error: deps/build/windows.debug.x86_64.dir/openssl/libssl.a: No such file or directory
x86_64-w64-mingw32-g++: error: deps/build/windows.debug.x86_64.dir/openssl/libcrypto.a: No such file or directory
scons: *** [bin/extension/webrtc_debug/lib/libwebrtc_native.windows.debug.x86_64.dll] Error 1
scons: building terminated because of errors.

### Steps to reproduce

Trying to build for beta2, only updated godot-cpp to correct commit

**Comment by maxim-sheronov** [comment]
Well, my bad.
I managed to build it for beta2. But it really could be great to have official build for every beta.

**Comment by Faless** [comment]
Yes, we definitely should have a build for every beta, I will try to make a build for beta 2 tomorrow, and keep it in sync with future betas.
The release script is mostly automated, but still requires manual re-upload of artifacts and adapting release notes.

**Comment by Heraclito-Q-Saldanha** [comment]
last build works until beta 16 but not beta 17

**Comment by Faless** [comment]
We now have a [stable release](https://github.com/godotengine/webrtc-native/releases/tag/1.0.0-stable) which should work with all Godot 4.0 patch releases (e.g. 4.0.1, 4.0.2, etc).
Closing as fixed.
