### ISSUE TITLE
Missing official Mac OSX plugin. (attached an unofficial one)

### ISSUE THREAD

**Issue by tomoprime** [godotengine/webrtc-native#8]
Just a heads up. The GDNative WebRTC plugin for Mac works on the official Godot 3.2 Alpha 3 release. I quickly tested the bomber-rtc demo with remote signaling. I thought I should share this as it took a few tweaks and over 20GB of disk space to build it all out. :sweat_smile:

[webrtc_0.3_mac_only-with-debug.zip](https://github.com/godotengine/webrtc-native/files/3796078/webrtc_0.3_mac_only-with-debug.zip)
[webrtc_0.3_multi-release.zip](https://github.com/godotengine/webrtc-native/files/3796091/webrtc_0.3_multi-release.zip)

**Comment by Faless** [comment]
Thank you a lot, I'm still trying to get my hands on a Mac to make an
official build :-(

**Comment by tomoprime** [comment]
Np I'll help where I can. Do you want the webrtcbuilds lib for OSX? It's ~268mb zipped so I doubt I can upload it here...

**Comment by Koyper** [comment]
Thank you for this. I've been unable to get a build to finish. What did you have to tweak?

**Comment by ImUrX** [comment]
Someday

**Comment by Faless** [comment]
The OSX target has now been added to the [`0.5 release`](https://github.com/godotengine/webrtc-native/releases/tag/0.5). Closing as fixed.
