### ISSUE TITLE
When launching the app around 10 times from the editor, there is approximately 1 constant error _create_offer: Failed to gather local ICE candidates

### ISSUE THREAD

**Issue by XDRiVE888** [godotengine/webrtc-native#88]
### Godot version

v3.5.2.stable.official [170ba337a]

### Plugin version

all v1.0.0 (rc,beta with libdatachannel)

### System information

Windows 10, 64bit

### Issue description

When launching the app around 10 times from the editor, there is approximately 1 constant error _create_offer: Failed to gather local ICE candidates <C++ source code>src/WebRTCLibPeerConnection.cpp:209 @ _create_offer().
I mean, in order to catch this error, you need to restart the application 10 times from the Godot editor, and not repeat the code itself 10 times. And as soon as an error occurs, all subsequent repetitions of the code also cause an error.
I also want to note that this error appears only in version v1.0.0 with libdatachannel and is not present in version 0.5 - WebRTC 4472.

### Steps to reproduce

To catch this error, you need to restart the application about 10 times from the Godot editor with this code:
```gdscript
	for _i in 5:
		var wc1:WebRTCPeerConnection = WebRTCPeerConnection.new()
		var err1
		err1 = wc1.initialize()
		if err1 == OK:
			var channel:WebRTCDataChannel = wc1.create_data_channel("play",{"id": 1, "negotiated": true})
			if channel != null:
				err1 = wc1.create_offer()
				if err1 != OK:
					print_debug("Periodic Error!!!")
```

**Comment by Faless** [comment]
I'm unable to reproduce using the latest plugin version [1.0.4](https://github.com/godotengine/webrtc-native/releases/tag/1.0.4-stable), and Godot 3.5.3/4.2.1 .

Can you confirm if this is still an issue?

**Comment by XDRiVE888** [comment]
> I'm unable to reproduce using the latest plugin version [1.0.4](https://github.com/godotengine/webrtc-native/releases/tag/1.0.4-stable), and Godot 3.5.3/4.2.1 .
> 
> Can you confirm if this is still an issue?

I checked with version 1.0.4 on Godot 3.5.3 and indeed I did not find this bug. It looks like this issue can be closed.

**Comment by XDRiVE888** [comment]
I unfortunately discovered that this error still pops up with variable randomness (from about 1 to 10,000 or more attempts) and to explicitly detect it I used this code:

```gdscript
func _ready():
	var errMax:int = 10
	for _i in 10000:
		var wc1:WebRTCPeerConnection = WebRTCPeerConnection.new()
		var err1
		err1 = wc1.initialize()
		if err1 == OK:
			var channel:WebRTCDataChannel = wc1.create_data_channel("play",{"id": 1, "negotiated": true})
			if channel != null:
				err1 = wc1.create_offer()
				if err1 != OK:
					print_debug("Periodic Error!!!:_i:",_i)
					errMax -= 1
					if errMax <= 0:
						break
		wc1 = null
