### ISSUE TITLE
iOS and Android target?

### ISSUE THREAD

**Issue by shintiger** [godotengine/webrtc-native#9]
Is there any idea for iOS and Android? Is it not in consideration or something long story to implement?

**Comment by Faless** [comment]
Well, we want to support WebRTC on those platforms in the future.

Android might be easier mainly because I don't have access to Apple devices (which is also the reason why there is not yet an official OSX build), but they both requires some work.

Overall, in the long run, I'd like to try and include [rawrtc](https://github.com/rawrtc/rawrtc) in Godot as a third party library which is much more lightweight only supports data channels (and will compile natively on all platform without the need for this GDNative plugin).

**Comment by shintiger** [comment]
Awesome news for me if don't required to build from GDNative for official API, or even chromium branch.

**Comment by Nachocss** [comment]
Hello, I was testing my game for the first time in Android and according to Godot's debugger there is no implementation defined yet. 
Are you planning to add it soon? @Faless

**Comment by Cevantime** [comment]
Same question here @Faless  ! And by the way, thank you so mush for your work. I'd be very glad to help, but I honestly don't even know where to start.

**Comment by Faless** [comment]
> Are you planning to add it soon?

Not really, it's something we'd like to have, but it's not in the top priorities right now.
Of course, if someone manages to build the android/iOS version correctly and posts the instructions I'll gladly add it to the releases.
The long term plan, as mentioned above, is to switch to a different, maintainable library, currently, both rawrtc and the amazon kinesis webrtc sdk are being evaluated.

**Comment by rondao** [comment]
Hey everyone, I've created #24 adding build support for Android.

I followed the [README.md](https://github.com/godotengine/webrtc-native/blob/master/README.md) build guide, using the following [WebRTC pre-compiled binaries](https://github.com/Faless/webrtc-builds/releases) for Android `arm` and `arm64`.

To build for Android, I've added `platform=android`.
`ANDROID_NDK_ROOT` env variable needs to be defined.

By default, it builds for `armv7` with Api 18.
To build for `arm64v8` (or x86, x86_64), use `android_arch=arm64v8`.

64 bits requires at least Api level 21.
If needed, you can change it with `android_api_level=XX`.

To be honest, I mostly used the [godot-cpp/SConstruct](https://github.com/godotengine/godot-cpp/blob/7cbb846417acf0154a786bcaee8a5b1d7b40df57/SConstruct) as reference. So may not be the best approach.

I've used a Linux (Ubuntu) host platform and built libraries for Android `armv7` and `arm64v8`.
I have not tested building from Windows or Mac. I also have not tested building for Android `x86` and `x86_64`.

I've tested the Android library with Godot [webrtc_signaling example](https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_signaling), It worked correctly locally on a Android device.
It also worked correctly between the Android device and a local Linux and HTML5 instance of the game.

Hope it helps.

**Comment by Faless** [comment]
Both Android and iOS targets have now been added to the [`0.5 release`](https://github.com/godotengine/webrtc-native/releases/tag/0.5). Closing as fixed.
