### ISSUE TITLE
Make builds for major and minor releases

### ISSUE THREAD

**Issue by carlos-ramos-73** [godotengine/webrtc-native#90]
### Godot version

4.0.0, 4.0.1, 4.0.2, 3.5.2, etc.

### Plugin version

latest

### System information

All

### Issue description

It would be nice to have the builds for major and minor releases of Godot 4 (also 3).
We are making a plugin that requires WebRTC on all supported platforms and well, that requires the builds for each platform.
To my understanding there is already a build script, but still requires some manual work for upload.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Faless** [comment]
The idea with GDNative/GDExtension is that they should be compatible across minor release.
So, the current version, should work for minor releases too (3.5.x and 4.0.x).
Did you encounter crashes/issues with the current plugin in the latest 3.5.x and 4.0.x?

**Comment by carlos-ramos-73** [comment]
Hey Fabio,

Thanks for the clarification.
I haven't properly tested the GDExtension in our plugin as it is WIP right now and I am just going through a design checklist.
So my apologies if I jumped the gun here.
The release notes does mention it might not work with different versions, but I understand that does not have to be the case.
But it has been a while from since 4.0-rc1, and with the official release out, I think it is not a bad idea to have a new build.

If you don't think its necessary, then you can close this. And I'll just report any issues along the way.
Thanks!

**Comment by Faless** [comment]
We now have a stable release which should work with all Godot 4.0 patch releases (e.g. 4.0.1, 4.0.2, etc).
The 3.5 version should already work across patch releases.
Closing as fixed.
