### ISSUE TITLE
Release export crash

### ISSUE THREAD

**Issue by Trey2k** [godotengine/webrtc-native#92]
### Godot version

v4.0.2.stable

### Plugin version

v1.0.0-rc1

### System information

Arch linux: 6.3.2-arch1-1

### Issue description

When exporting a game as release not debug it will crash when a connection is attempted:
![image](https://github.com/godotengine/webrtc-native/assets/7241029/ee544127-bc1c-47f4-b4cf-c187ece31717)

### Steps to reproduce

- Download the [webrtc_minimal](https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_minimal) project from the [godot-demo-projects](https://github.com/godotengine/godot-demo-projects) repo.
- Download v1.0.0-rc1 of webrtc-native GDExtension.
- Export project without debugging
- Run

### Minimal reproduction project

https://github.com/godotengine/godot-demo-projects/tree/master/networking/webrtc_minimal

**Comment by Trey2k** [comment]
Windows releases also crash.

**Comment by Faless** [comment]
Thanks for reporting, I've confirmed the issue, this seems to have been fixed in upstream godot-cpp via https://github.com/godotengine/godot-cpp/pull/1053 .

I've opened #93 to update godot-cpp to `4.0-stable`.

I'll prepare a new release shortly.

**Comment by Trey2k** [comment]
I am able to confirm the new build from actions works as expected in a release export. Thanks for the quick fix!

**Comment by Faless** [comment]
Closing as fixed via https://github.com/godotengine/webrtc-native/pull/93, a new stable release is available which includes the fix.
